/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to
 * https://docs.gradle.org/8.5/userguide/building_java_projects.html in the Gradle documentation.
 */
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.TaskAction
import org.gradle.api.tasks.OutputFile
import org.gradle.api.provider.Property
import java.io.File
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter
import java.io.FileOutputStream
import java.util.Properties

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    java
    application
    id("com.github.johnrengelman.shadow") version "8.1.1"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
    implementation("org.apache.commons:commons-lang3:3.16.0")
    implementation("ch.qos.logback:logback-classic:1.4.11")
    implementation("org.slf4j:slf4j-api:2.0.11")
    implementation(project(":string-utils"))
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

application {
    // Define the main class for the application.
    mainClass.set("lab.App")
    mainClass = "org.example.Main"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

tasks.shadowJar {
    manifest {
        attributes["Main-Class"] = "org.example.Main"
    }
}

// Определяем новый класс задачи
abstract class PrintInfoTask : DefaultTask() {
    @TaskAction
    fun print() {
        println("======================================")
        println("Это моя первая пользовательская задача!")
        println("Проект: ${project.name}")
        println("Версия Gradle: ${project.gradle.gradleVersion}")
        println("======================================")
    }
}

// Регистрируем задачу printInfo
tasks.register<PrintInfoTask>("printInfo") {
    group = "Custom"  // Группа задач
    description = "Выводит информацию о проекте"  // Описание задачи
}

// Определяем класс задачи для генерации build passport с номером сборки и git hash
abstract class GenerateBuildInfoTask : DefaultTask() {
    
    @get:Input
    abstract val gitCommitHash: Property<String>
    
    @get:OutputFile
    val outputFile: File = project.buildDir.resolve("resources/main/build-passport.properties")
    
    @TaskAction
    fun generate() {
        // Получаем хеш последнего коммита
        val commitHash = gitCommitHash.getOrElse(getGitCommitHash())
        
        // Работа с номером сборки
        val buildNumberFile = project.rootProject.file("build.number")
        val buildNumber = getNextBuildNumber(buildNumberFile)
        
        // Создаем Properties объект
        val props = Properties()
        
        // Добавляем информацию
        props.setProperty("build.user", System.getenv("USERNAME") ?: System.getenv("USER") ?: "unknown")
        props.setProperty("build.os", System.getProperty("os.name") ?: "unknown")
        props.setProperty("build.java.version", System.getProperty("java.version") ?: "unknown")
        props.setProperty("build.time", LocalDateTime.now().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME))
        props.setProperty("build.message", "Hello from Gradle build!")
        props.setProperty("build.git.commit", commitHash)
        props.setProperty("build.number", buildNumber.toString())
        
        // Создаем директорию, если её нет
        outputFile.parentFile.mkdirs()
        
        // Сохраняем properties файл
        FileOutputStream(outputFile).use { 
            props.store(it, "Build Passport") 
        }
        
        println("Build passport generated with number: $buildNumber, commit: $commitHash")
    }
    
    private fun getGitCommitHash(): String {
        return try {
            val process = ProcessBuilder("git", "rev-parse", "HEAD")
                .directory(project.rootProject.projectDir)
                .redirectErrorStream(true)
                .start()
            
            process.inputStream.bufferedReader().readText().trim()
        } catch (e: Exception) {
            println("Warning: Could not get git commit hash: ${e.message}")
            "unknown"
        }
    }
    
    private fun getNextBuildNumber(buildNumberFile: File): Int {
        val currentNumber = if (buildNumberFile.exists()) {
            buildNumberFile.readText().trim().toIntOrNull() ?: 0
        } else {
            0
        }
        
        val nextNumber = currentNumber + 1
        buildNumberFile.writeText(nextNumber.toString())
        
        return nextNumber
    }
}

// Регистрация задачи generateBuildInfo с правильным получением git hash
tasks.register<GenerateBuildInfoTask>("generateBuildInfo") {
    gitCommitHash.set(project.provider { 
        try {
            val process = ProcessBuilder("git", "rev-parse", "HEAD")
                .directory(project.rootProject.projectDir)
                .redirectErrorStream(true)
                .start()
            
            process.inputStream.bufferedReader().use { reader ->
                reader.readText().trim()
            }
        } catch (e: Exception) {
            println("Warning: Could not get git commit hash: ${e.message}")
            "unknown"
        }
    })
    
    // Убеждаемся, что задача выполняется перед компиляцией
    mustRunAfter("clean")
}

// Настраиваем выполнение задачи при сборке
tasks.named("processResources") {
    dependsOn("generateBuildInfo")
}